# Run Travis CI for R using https://eddelbuettel.github.io/r-travis/

language: r

sudo: required

dist: bionic

jobs:
  include:
    #- name: r-3.5
    #  env: R_VERSION="3.5"
    - name: r-4.0
      env: R_VERSION="4.0"

env:
  global:
    - RunAllRcppAnnoyTests="yes"

before_install:
  - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  - ./run.sh bootstrap

install:
  - ./run.sh install_aptget libgsl0-dev r-cran-rcpp r-cran-mass r-cran-rcppgsl r-cran-tweedie r-cran-statmod r-cran-testthat

before_script: 
  - Rscript -e "install.packages(c('Rcpp', 'RcppEigen', 'RcppNumerical', 'DistributionUtils', 'mixtools', 'knitr', 'ggplot2', 'dplyr', 'tidyr'), repos='https://cloud.r-project.org/')"

script:
  - ./run.sh run_tests

after_failure:
  - ./run.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

